### ISSUE TITLE
Installer doesn’t work.

### ISSUE THREAD

**Issue by cdez-cactus-os** [cdez-cactus-os/Cactus-OS-for-ComputerCraft#8]
For whatever reason I can’t get it to work, is there a dependance that I’m missing? Like on ComputerCraft?

**Comment by LDDestroier** [comment]
No no no, I must've made a mistake when making it. I'll try getting it working shortly.

**Comment by LDDestroier** [comment]
It should be fixed by the way. Thanks to apemanzilla's code.

**Comment by cdez-cactus-os** [comment]
Thank you!
